=== cvsco/paTetris/TetrisGame/myfiles/configparameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ConfigParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="userDB" type="xs:string"/>
				<xs:element name="passwordDB" type="xs:string"/>
				<xs:element name="ipServerLog" type="xs:string"/>
				<xs:element name="portServerLog" type="xs:int"/>
				<xs:element name="ipClient" type="xs:string"/>
				<xs:element name="rankingTopX" type="xs:int"/>
				<xs:element name="startLevel" type="xs:int"/>
				<xs:element name="windowColor" type="xs:string"/>
				<xs:element name="playingFieldColor" type="xs:string"/>
				<xs:element name="textFont" type="xs:string"/>
				<xs:element name="textSize" type="xs:int"/>
				<xs:element name="textColor" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="ipDB" type="xs:string" use="required"/>
			<xs:attribute name="portDB" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
 </xs:schema>

=== cvsco/paTetris/TetrisGame/myfiles/configparameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- configparameters.xml 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configparameters.xsd"-->
<ConfigParameters ipDB="127.0.0.1" portDB="3306" >
	<userDB>root</userDB>
	<passwordDB></passwordDB>
	<ipServerLog>127.0.0.1</ipServerLog>
	<portServerLog>8080</portServerLog>
	<ipClient>127.0.0.1</ipClient>
	<rankingTopX>10</rankingTopX>
	<startLevel>1</startLevel>
	<windowColor>#282F3E</windowColor>
	<playingFieldColor>#10141c</playingFieldColor>
	<textFont>Helvetica</textFont>
	<textSize>15</textSize>
	<textColor>#f08414</textColor>
</ConfigParameters>
